[build]
target = "x86_64-unknown-linux-gnu"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-nostdlib",
    "-C", "link-arg=-nostartfiles",
]
